INSTRUMENTS = {
    'XAUUSD': {
        'name': 'Gold Spot',
        'category': 'metal',
        'pip_size': 0.01,
        'pip_value_usd': 1.0,
        'contract_multiplier': 100,
        'margin_pct': 0.01,
        'spread_avg': 3.0,
        'slippage_pct': 0.0001,
        'swap_long': -3.5,
        'swap_short': 1.5,
        'min_volume': 0.01,
        'max_volume': 100.0,
        'volume_step': 0.01,
        'leverage_max': 100,
        'currency': 'USD',
        'hours': '24h Sun-Thu',
    },
    'XAGUSD': {
        'name': 'Silver Spot',
        'category': 'metal',
        'pip_size': 0.001,
        'pip_value_usd': 5.0,
        'contract_multiplier': 5000,
        'margin_pct': 0.02,
        'spread_avg': 5.0,
        'slippage_pct': 0.0002,
        'swap_long': -2.0,
        'swap_short': 0.5,
        'min_volume': 0.01,
        'max_volume': 100.0,
        'volume_step': 0.01,
        'leverage_max': 50,
        'currency': 'USD',
    },
    'EURUSD': {
        'name': 'Euro vs US Dollar',
        'category': 'forex',
        'pip_size': 0.0001,
        'pip_value_usd': 10.0,
        'contract_multiplier': 100000,
        'margin_pct': 0.002,
        'spread_avg': 0.2,
        'slippage_pct': 0.00002,
        'swap_long': -5.0,
        'swap_short': 0.5,
        'min_volume': 0.01,
        'max_volume': 100.0,
        'volume_step': 0.01,
        'leverage_max': 500,
        'currency': 'USD',
    },
    'GBPUSD': {
        'name': 'British Pound vs US Dollar',
        'category': 'forex',
        'pip_size': 0.0001,
        'pip_value_usd': 10.0,
        'contract_multiplier': 100000,
        'margin_pct': 0.002,
        'spread_avg': 0.3,
        'slippage_pct': 0.00002,
        'swap_long': -4.0,
        'swap_short': 1.0,
        'min_volume': 0.01,
        'max_volume': 100.0,
        'volume_step': 0.01,
        'leverage_max': 500,
        'currency': 'USD',
    },
    'USDJPY': {
        'name': 'US Dollar vs Japanese Yen',
        'category': 'forex',
        'pip_size': 0.01,
        'pip_value_usd': 9.5,
        'contract_multiplier': 100000,
        'margin_pct': 0.002,
        'spread_avg': 0.3,
        'slippage_pct': 0.00002,
        'swap_long': -4.5,
        'swap_short': 1.5,
        'min_volume': 0.01,
        'max_volume': 100.0,
        'volume_step': 0.01,
        'leverage_max': 500,
        'currency': 'USD',
    },
    'AUDUSD': {
        'name': 'Australian Dollar vs US Dollar',
        'category': 'forex',
        'pip_size': 0.0001,
        'pip_value_usd': 10.0,
        'contract_multiplier': 100000,
        'margin_pct': 0.002,
        'spread_avg': 0.4,
        'slippage_pct': 0.00002,
        'swap_long': -3.0,
        'swap_short': 0.5,
        'min_volume': 0.01,
        'max_volume': 100.0,
        'volume_step': 0.01,
        'leverage_max': 500,
        'currency': 'USD',
    },
    'NZDUSD': {
        'name': 'New Zealand Dollar vs US Dollar',
        'category': 'forex',
        'pip_size': 0.0001,
        'pip_value_usd': 10.0,
        'contract_multiplier': 100000,
        'margin_pct': 0.002,
        'spread_avg': 0.5,
        'slippage_pct': 0.00002,
        'swap_long': -2.5,
        'swap_short': 0.5,
        'min_volume': 0.01,
        'max_volume': 100.0,
        'volume_step': 0.01,
        'leverage_max': 500,
        'currency': 'USD',
    },
    'USDCHF': {
        'name': 'US Dollar vs Swiss Franc',
        'category': 'forex',
        'pip_size': 0.0001,
        'pip_value_usd': 10.0,
        'contract_multiplier': 100000,
        'margin_pct': 0.002,
        'spread_avg': 0.3,
        'slippage_pct': 0.00002,
        'swap_long': -4.0,
        'swap_short': 1.0,
        'min_volume': 0.01,
        'max_volume': 100.0,
        'volume_step': 0.01,
        'leverage_max': 500,
        'currency': 'USD',
    },
    'USDCAD': {
        'name': 'US Dollar vs Canadian Dollar',
        'category': 'forex',
        'pip_size': 0.0001,
        'pip_value_usd': 10.0,
        'contract_multiplier': 100000,
        'margin_pct': 0.002,
        'spread_avg': 0.4,
        'slippage_pct': 0.00002,
        'swap_long': -3.0,
        'swap_short': 0.5,
        'min_volume': 0.01,
        'max_volume': 100.0,
        'volume_step': 0.01,
        'leverage_max': 500,
        'currency': 'USD',
    },
    'EURGBP': {
        'name': 'Euro vs British Pound',
        'category': 'forex',
        'pip_size': 0.0001,
        'pip_value_usd': 10.0,
        'contract_multiplier': 100000,
        'margin_pct': 0.002,
        'spread_avg': 0.4,
        'slippage_pct': 0.00002,
        'swap_long': -3.5,
        'swap_short': 0.5,
        'min_volume': 0.01,
        'max_volume': 100.0,
        'volume_step': 0.01,
        'leverage_max': 500,
        'currency': 'USD',
    },
    'EURJPY': {
        'name': 'Euro vs Japanese Yen',
        'category': 'forex',
        'pip_size': 0.01,
        'pip_value_usd': 9.0,
        'contract_multiplier': 100000,
        'margin_pct': 0.002,
        'spread_avg': 0.5,
        'slippage_pct': 0.00002,
        'swap_long': -4.0,
        'swap_short': 1.0,
        'min_volume': 0.01,
        'max_volume': 100.0,
        'volume_step': 0.01,
        'leverage_max': 500,
        'currency': 'USD',
    },
    'GBPJPY': {
        'name': 'British Pound vs Japanese Yen',
        'category': 'forex',
        'pip_size': 0.01,
        'pip_value_usd': 9.0,
        'contract_multiplier': 100000,
        'margin_pct': 0.002,
        'spread_avg': 0.6,
        'slippage_pct': 0.00003,
        'swap_long': -5.0,
        'swap_short': 1.5,
        'min_volume': 0.01,
        'max_volume': 100.0,
        'volume_step': 0.01,
        'leverage_max': 500,
        'currency': 'USD',
    },
    'BTCUSD': {
        'name': 'Bitcoin vs US Dollar',
        'category': 'crypto',
        'pip_size': 1.0,
        'pip_value_usd': 0.1,
        'contract_multiplier': 1,
        'margin_pct': 0.05,
        'spread_avg': 5.0,
        'slippage_pct': 0.0005,
        'swap_long': -10.0,
        'swap_short': 5.0,
        'min_volume': 0.001,
        'max_volume': 100.0,
        'volume_step': 0.001,
        'leverage_max': 20,
        'currency': 'USD',
    },
    'ETHUSD': {
        'name': 'Ethereum vs US Dollar',
        'category': 'crypto',
        'pip_size': 0.01,
        'pip_value_usd': 0.1,
        'contract_multiplier': 1,
        'margin_pct': 0.05,
        'spread_avg': 3.0,
        'slippage_pct': 0.0005,
        'swap_long': -8.0,
        'swap_short': 4.0,
        'min_volume': 0.001,
        'max_volume': 100.0,
        'volume_step': 0.001,
        'leverage_max': 20,
        'currency': 'USD',
    },
    'SOLUSD': {
        'name': 'Solana vs US Dollar',
        'category': 'crypto',
        'pip_size': 0.01,
        'pip_value_usd': 0.1,
        'contract_multiplier': 1,
        'margin_pct': 0.05,
        'spread_avg': 4.0,
        'slippage_pct': 0.001,
        'swap_long': -6.0,
        'swap_short': 3.0,
        'min_volume': 0.001,
        'max_volume': 100.0,
        'volume_step': 0.001,
        'leverage_max': 20,
        'currency': 'USD',
    },
    'XRPUSD': {
        'name': 'Ripple vs US Dollar',
        'category': 'crypto',
        'pip_size': 0.0001,
        'pip_value_usd': 0.1,
        'contract_multiplier': 1,
        'margin_pct': 0.05,
        'spread_avg': 2.0,
        'slippage_pct': 0.0005,
        'swap_long': -5.0,
        'swap_short': 2.5,
        'min_volume': 0.001,
        'max_volume': 100.0,
        'volume_step': 0.001,
        'leverage_max': 20,
        'currency': 'USD',
    },
    'DOGEUSD': {
        'name': 'Dogecoin vs US Dollar',
        'category': 'crypto',
        'pip_size': 0.00001,
        'pip_value_usd': 0.1,
        'contract_multiplier': 1,
        'margin_pct': 0.1,
        'spread_avg': 5.0,
        'slippage_pct': 0.001,
        'swap_long': -4.0,
        'swap_short': 2.0,
        'min_volume': 0.001,
        'max_volume': 100.0,
        'volume_step': 0.001,
        'leverage_max': 10,
        'currency': 'USD',
    },
    'ADAUSD': {
        'name': 'Cardano vs US Dollar',
        'category': 'crypto',
        'pip_size': 0.0001,
        'pip_value_usd': 0.1,
        'contract_multiplier': 1,
        'margin_pct': 0.05,
        'spread_avg': 3.0,
        'slippage_pct': 0.0005,
        'swap_long': -5.0,
        'swap_short': 2.5,
        'min_volume': 0.001,
        'max_volume': 100.0,
        'volume_step': 0.001,
        'leverage_max': 20,
        'currency': 'USD',
    },
    'BNBUSD': {
        'name': 'Binance Coin vs US Dollar',
        'category': 'crypto',
        'pip_size': 0.01,
        'pip_value_usd': 0.1,
        'contract_multiplier': 1,
        'margin_pct': 0.05,
        'spread_avg': 4.0,
        'slippage_pct': 0.0005,
        'swap_long': -6.0,
        'swap_short': 3.0,
        'min_volume': 0.001,
        'max_volume': 100.0,
        'volume_step': 0.001,
        'leverage_max': 20,
        'currency': 'USD',
    },
    'LINKUSD': {
        'name': 'Chainlink vs US Dollar',
        'category': 'crypto',
        'pip_size': 0.001,
        'pip_value_usd': 0.1,
        'contract_multiplier': 1,
        'margin_pct': 0.05,
        'spread_avg': 3.0,
        'slippage_pct': 0.0005,
        'swap_long': -5.0,
        'swap_short': 2.5,
        'min_volume': 0.001,
        'max_volume': 100.0,
        'volume_step': 0.001,
        'leverage_max': 20,
        'currency': 'USD',
    },
    'LTCUSD': {
        'name': 'Litecoin vs US Dollar',
        'category': 'crypto',
        'pip_size': 0.01,
        'pip_value_usd': 0.1,
        'contract_multiplier': 1,
        'margin_pct': 0.05,
        'spread_avg': 3.0,
        'slippage_pct': 0.0005,
        'swap_long': -5.0,
        'swap_short': 2.5,
        'min_volume': 0.001,
        'max_volume': 100.0,
        'volume_step': 0.001,
        'leverage_max': 20,
        'currency': 'USD',
    },
    'DOTUSD': {
        'name': 'Polkadot vs US Dollar',
        'category': 'crypto',
        'pip_size': 0.001,
        'pip_value_usd': 0.1,
        'contract_multiplier': 1,
        'margin_pct': 0.05,
        'spread_avg': 4.0,
        'slippage_pct': 0.0005,
        'swap_long': -5.0,
        'swap_short': 2.5,
        'min_volume': 0.001,
        'max_volume': 100.0,
        'volume_step': 0.001,
        'leverage_max': 20,
        'currency': 'USD',
    },
    'NAS100': {
        'name': 'US Nasdaq 100 Index',
        'category': 'index',
        'pip_size': 0.1,
        'pip_value_usd': 1.0,
        'contract_multiplier': 10,
        'margin_pct': 0.01,
        'spread_avg': 1.5,
        'slippage_pct': 0.0002,
        'swap_long': -2.0,
        'swap_short': 0.5,
        'min_volume': 0.1,
        'max_volume': 100.0,
        'volume_step': 0.1,
        'leverage_max': 100,
        'currency': 'USD',
    },
    'US30': {
        'name': 'US Dow Jones 30 Index',
        'category': 'index',
        'pip_size': 0.1,
        'pip_value_usd': 1.0,
        'contract_multiplier': 10,
        'margin_pct': 0.01,
        'spread_avg': 2.0,
        'slippage_pct': 0.0002,
        'swap_long': -2.5,
        'swap_short': 0.5,
        'min_volume': 0.1,
        'max_volume': 100.0,
        'volume_step': 0.1,
        'leverage_max': 100,
        'currency': 'USD',
    },
    'US500': {
        'name': 'US S&P 500 Index',
        'category': 'index',
        'pip_size': 0.1,
        'pip_value_usd': 1.0,
        'contract_multiplier': 10,
        'margin_pct': 0.01,
        'spread_avg': 1.5,
        'slippage_pct': 0.0002,
        'swap_long': -2.0,
        'swap_short': 0.5,
        'min_volume': 0.1,
        'max_volume': 100.0,
        'volume_step': 0.1,
        'leverage_max': 100,
        'currency': 'USD',
    },
    'GER40': {
        'name': 'Germany DAX 40 Index',
        'category': 'index',
        'pip_size': 0.1,
        'pip_value_usd': 1.0,
        'contract_multiplier': 10,
        'margin_pct': 0.01,
        'spread_avg': 2.0,
        'slippage_pct': 0.0002,
        'swap_long': -2.5,
        'swap_short': 0.5,
        'min_volume': 0.1,
        'max_volume': 100.0,
        'volume_step': 0.1,
        'leverage_max': 100,
        'currency': 'EUR',
    },
    'UK100': {
        'name': 'UK FTSE 100 Index',
        'category': 'index',
        'pip_size': 0.1,
        'pip_value_usd': 1.0,
        'contract_multiplier': 10,
        'margin_pct': 0.01,
        'spread_avg': 2.0,
        'slippage_pct': 0.0002,
        'swap_long': -2.0,
        'swap_short': 0.5,
        'min_volume': 0.1,
        'max_volume': 100.0,
        'volume_step': 0.1,
        'leverage_max': 100,
        'currency': 'GBP',
    },
    'FRA40': {
        'name': 'France CAC 40 Index',
        'category': 'index',
        'pip_size': 0.1,
        'pip_value_usd': 1.0,
        'contract_multiplier': 10,
        'margin_pct': 0.01,
        'spread_avg': 2.0,
        'slippage_pct': 0.0002,
        'swap_long': -2.0,
        'swap_short': 0.5,
        'min_volume': 0.1,
        'max_volume': 100.0,
        'volume_step': 0.1,
        'leverage_max': 100,
        'currency': 'EUR',
    },
    'JPN225': {
        'name': 'Japan Nikkei 225 Index',
        'category': 'index',
        'pip_size': 0.1,
        'pip_value_usd': 1.0,
        'contract_multiplier': 10,
        'margin_pct': 0.01,
        'spread_avg': 3.0,
        'slippage_pct': 0.0002,
        'swap_long': -2.0,
        'swap_short': 0.5,
        'min_volume': 0.1,
        'max_volume': 100.0,
        'volume_step': 0.1,
        'leverage_max': 100,
        'currency': 'JPY',
    },
    'HK50': {
        'name': 'Hong Kong Hang Seng Index',
        'category': 'index',
        'pip_size': 0.1,
        'pip_value_usd': 1.0,
        'contract_multiplier': 10,
        'margin_pct': 0.02,
        'spread_avg': 3.0,
        'slippage_pct': 0.0003,
        'swap_long': -2.0,
        'swap_short': 0.5,
        'min_volume': 0.1,
        'max_volume': 100.0,
        'volume_step': 0.1,
        'leverage_max': 50,
        'currency': 'HKD',
    },
    'OIL': {
        'name': 'West Texas Intermediate Crude Oil',
        'category': 'commodity',
        'pip_size': 0.01,
        'pip_value_usd': 10.0,
        'contract_multiplier': 1000,
        'margin_pct': 0.02,
        'spread_avg': 3.0,
        'slippage_pct': 0.0003,
        'swap_long': -4.0,
        'swap_short': 1.0,
        'min_volume': 0.1,
        'max_volume': 100.0,
        'volume_step': 0.1,
        'leverage_max': 50,
        'currency': 'USD',
    },
    'BRENT': {
        'name': 'Brent Crude Oil',
        'category': 'commodity',
        'pip_size': 0.01,
        'pip_value_usd': 10.0,
        'contract_multiplier': 1000,
        'margin_pct': 0.02,
        'spread_avg': 3.0,
        'slippage_pct': 0.0003,
        'swap_long': -4.0,
        'swap_short': 1.0,
        'min_volume': 0.1,
        'max_volume': 100.0,
        'volume_step': 0.1,
        'leverage_max': 50,
        'currency': 'USD',
    },
    'GAS': {
        'name': 'Natural Gas',
        'category': 'commodity',
        'pip_size': 0.001,
        'pip_value_usd': 10.0,
        'contract_multiplier': 10000,
        'margin_pct': 0.05,
        'spread_avg': 5.0,
        'slippage_pct': 0.0005,
        'swap_long': -3.0,
        'swap_short': 0.5,
        'min_volume': 0.1,
        'max_volume': 100.0,
        'volume_step': 0.1,
        'leverage_max': 20,
        'currency': 'USD',
    },
}

TIMEFRAME_MAP = {
    '1m': 1, '5m': 5, '15m': 15, '30m': 30,
    '1h': 60, '4h': 240, '1d': 1440, '1w': 10080,
}

def get_instrument(symbol: str) -> dict:
    return INSTRUMENTS.get(symbol.upper())

def get_pip_value(symbol: str, price: float = None) -> float:
    inst = get_instrument(symbol)
    if not inst:
        return 0.0001
    return inst['pip_size']

def price_to_pips(symbol: str, price_diff: float) -> float:
    inst = get_instrument(symbol)
    if not inst:
        return price_diff / 0.0001
    return price_diff / inst['pip_size']

def pips_to_price(symbol: str, pips: float) -> float:
    inst = get_instrument(symbol)
    if not inst:
        return pips * 0.0001
    return pips * inst['pip_size']

def compute_pnl(symbol: str, entry_price: float, exit_price: float, volume: float, is_buy: bool) -> float:
    inst = get_instrument(symbol)
    if not inst:
        diff = (exit_price - entry_price) if is_buy else (entry_price - exit_price)
        return diff * volume * 100000
    diff = (exit_price - entry_price) if is_buy else (entry_price - exit_price)
    return diff * volume * inst['contract_multiplier']
